# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-FastCGI
version:      0.01
version_from: lib/CGI/Application/FastCGI.pm
installdirs:  site
requires:
    CGI::Application:              3
    FCGI:                          0.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
